- type: replace
  path: /vm_types/name=default/cloud_properties
  value:
    instance_type: Standard_D1_v2

- type: replace
  path: /networks/name=private/subnets/0/cloud_properties
  value:
    virtual_network_name: ((vnet_name))
    subnet_name: ((subnet_name))
