---
groups:
  - name: certify-vcloud
    jobs:
      - bats-v5.5
      - certification

jobs:
  - name: bats-v5.5
    serial_groups: [group-v5.5]
    plan:
      - aggregate:
        - {get: cpi-release,      tags: [vcloud-v5.5], trigger: true}
        - {get: bosh-release,     tags: [vcloud-v5.5], trigger: true}
        - {get: stemcell,         tags: [vcloud-v5.5], trigger: true}
        - {get: after-midnight,   tags: [vcloud-v5.5], trigger: true}
        - {get: pipelines,        tags: [vcloud-v5.5], trigger: false}
        - {get: bats,             tags: [vcloud-v5.5], trigger: false}
        - {get: bosh-cli,         tags: [vcloud-v5.5], trigger: false}

      - task: prepare-director
        file: pipelines/vcloud/tasks/prepare-director.yml
        tags: [vcloud-v5.5]
        params:
          VCLOUD_HOST:            {{VCLOUD_V5_5_HOST}}
          VCLOUD_USER:            {{VCLOUD_V5_5_USER}}
          VCLOUD_PASSWORD:        {{VCLOUD_V5_5_PASSWORD}}
          VCLOUD_VLAN:            {{VCLOUD_VLAN}}
          VCLOUD_ORG:             {{VCLOUD_V5_5_ORG}}
          VCLOUD_VDC:             {{VCLOUD_V5_5_VDC}}
          VCLOUD_VAPP:            {{VCLOUD_VAPP}}
          VCLOUD_CATALOG:         {{VCLOUD_CATALOG}}
          NETWORK_CIDR:           {{NETWORK_CIDR}}
          NETWORK_GATEWAY:        {{NETWORK_GATEWAY}}
          BATS_DIRECTOR_IP:       {{BATS_DIRECTOR_IP_ubuntu}}
          BOSH_CLIENT:            {{BOSH_CLIENT}}
          BOSH_CLIENT_SECRET:     {{BOSH_CLIENT_SECRET}}
          SSLIP_IO_KEY:           {{sslip_io_key}}

      - do:
        - task: deploy-director
          tags: [vcloud-v5.5]
          file: pipelines/shared/tasks/deploy-director.yml

        - task: prepare-bats
          tags: [vcloud-v5.5]
          file: pipelines/vcloud/tasks/prepare-bats.yml
          params:
            STEMCELL_NAME:          bosh-vcloud-esxi-ubuntu-trusty-go_agent
            VCLOUD_VLAN:            {{VCLOUD_VLAN}}
            VCLOUD_VAPP:            {{VCLOUD_VAPP}}
            NETWORK_CIDR:           {{NETWORK_CIDR}}
            NETWORK_GATEWAY:        {{NETWORK_GATEWAY}}
            BATS_DIRECTOR_IP:       {{BATS_DIRECTOR_IP_ubuntu}}
            BATS_IP1:               {{BATS_IP1_ubuntu}}
            BATS_IP2:               {{BATS_IP2_ubuntu}}
            BATS_RESERVED_RANGE1:   {{BATS_RESERVED_RANGE1_ubuntu}}
            BATS_RESERVED_RANGE2:   {{BATS_RESERVED_RANGE2_ubuntu}}
            BATS_STATIC_RANGE:      {{BATS_STATIC_RANGE_ubuntu}}
            BOSH_CLIENT:            {{BOSH_CLIENT}}
            BOSH_CLIENT_SECRET:     {{BOSH_CLIENT_SECRET}}

        - task: run-bats
          file: pipelines/shared/tasks/run-bats.yml
          tags: [vcloud-v5.5]

        ensure:
          task: teardown
          file: pipelines/shared/tasks/teardown.yml
          tags: [vcloud-v5.5]

  - name: certification
    plan:
      - aggregate:
        - {get: cpi-release,      tags: [vcloud-v5.5], trigger: true, passed: [bats-v5.5]}
        - {get: bosh-release,     tags: [vcloud-v5.5], trigger: true, passed: [bats-v5.5]}
        - {get: stemcell,         tags: [vcloud-v5.5], trigger: true, passed: [bats-v5.5]}
        - {get: pipelines,        tags: [vcloud-v5.5], trigger: false}

      - task: generate
        file: pipelines/shared/tasks/generate-receipt.yml
        tags: [vcloud-v5.5]
        params:
          CPI_RELEASE_NAME: bosh-vcloud-cpi
          STEMCELL_NAME:    bosh-vcloud-esxi-ubuntu-trusty-go_agent

      - {put: receipt, tags: [vcloud-v5.5], params: {file: certification/*-receipt.json}}

resources:
  - name: after-midnight
    type: time
    source:
      start: 12:00 AM -0700
      stop: 2:00 AM -0700

  - name: pipelines
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/bosh-cpi-certification
      branch: master

  - name: cpi-release
    type: bosh-io-release
    source:
      repository: cloudfoundry-incubator/bosh-vcloud-cpi-release

  - name: bosh-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/bosh

  - name: bats
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-acceptance-tests.git
      branch: master

  - name: stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-vcloud-esxi-ubuntu-trusty-go_agent

  - name: bosh-cli
    type: s3
    source:
      regexp: bosh-cli-([0-9.]+)-linux-amd64
      bucket: bosh-cli-artifacts
      region_name: us-east-1

  - name: receipt
    type: s3
    source:
      access_key_id: {{certification__bucket_access_key}}
      secret_access_key: {{certification__bucket_secret_key}}
      bucket: {{certification__bucket}}
      regexp: .*-(\d+)-receipt\.json
      region_name: us-east-1
