---
platform: linux
image_resource:
  type: docker-image
  source: {repository: boshcpi/cpi-certification}

inputs:
  - name: pipelines
  - name: bosh-release
  - name: cpi-release
  - name: stemcell
  - name: environment

outputs:
  - name: director-config

run:
  path: pipelines/aws/tasks/prepare-director.sh

params:
  AWS_ACCESS_KEY:         ""
  AWS_SECRET_KEY:         ""
  AWS_REGION_NAME:        ""
  BOSH_CLIENT:          ""
  BOSH_CLIENT_SECRET:        ""
  PUBLIC_KEY_NAME:        ""
  PRIVATE_KEY_DATA:       ""
  USE_REDIS:              ""
  SSLIP_IO_KEY:           ""
