---
platform: linux
image_resource:
  type: docker-image
  source: {repository: boshcpi/cpi-certification}

inputs:
  - name: pipelines
  - name: bosh-release
  - name: cpi-release
  - name: stemcell

outputs:
  - name: director-config

run:
  path: pipelines/aws/tasks/prepare-director-iam.sh

params:
  BOSH_CLIENT:            ""
  BOSH_CLIENT_SECRET:     ""
  AWS_ACCESS_KEY:         ""
  AWS_SECRET_KEY:         ""
  AWS_REGION_NAME:        ""
  AWS_STACK_NAME:         ""
  PUBLIC_KEY_NAME:        ""
  PRIVATE_KEY_DATA:       ""
  SSLIP_IO_KEY:           ""
